import turtle
t = turtle.Turtle()
my_turtle = turtle.Turtle()
t.speed(0)
t.penup()
t.goto(-50, 0)
t.pendown()
for _ in range(2):
    my_turtle.forward(100)
    my_turtle.right(90)
    my_turtle.forward(50)
    my_turtle.right(90)
my_turtle.penup()
my_turtle.forward(120)
my_turtle.pendown()
for _ in range(4):
    my_turtle.forward(50)
    my_turtle.right(90)
my_turtle.penup()
my_turtle.forward(80)
my_turtle.pendown()
my_turtle.circle(25)
my_turtle.penup()
my_turtle.forward(50)
my_turtle.right(30)
my_turtle.forward(43.3)
my_turtle.pendown()
for _ in range(3):
    my_turtle.forward(50)
    my_turtle.right(120)
